// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "exchange.proto" (package "com.psa", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Exchange } from "./exchange";
import type { GetSymbolResponse } from "./exchange";
import type { GetSymbolRequest } from "./exchange";
import type { GetMarketDepthResponse } from "./exchange";
import type { GetMarketDepthRequest } from "./exchange";
import type { GetOrdersResponse } from "./exchange";
import type { GetOrdersRequest } from "./exchange";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CreateOrderResponse } from "./exchange";
import type { CreateOrderRequest } from "./exchange";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service com.psa.Exchange
 */
export interface IExchangeClient {
    /**
     * @generated from protobuf rpc: CreateOrder(com.psa.CreateOrderRequest) returns (com.psa.CreateOrderResponse);
     */
    createOrder(input: CreateOrderRequest, options?: RpcOptions): UnaryCall<CreateOrderRequest, CreateOrderResponse>;
    /**
     * @generated from protobuf rpc: GetOrders(com.psa.GetOrdersRequest) returns (com.psa.GetOrdersResponse);
     */
    getOrders(input: GetOrdersRequest, options?: RpcOptions): UnaryCall<GetOrdersRequest, GetOrdersResponse>;
    /**
     * @generated from protobuf rpc: GetMarketDepth(com.psa.GetMarketDepthRequest) returns (com.psa.GetMarketDepthResponse);
     */
    getMarketDepth(input: GetMarketDepthRequest, options?: RpcOptions): UnaryCall<GetMarketDepthRequest, GetMarketDepthResponse>;
    /**
     * @generated from protobuf rpc: GetSymbol(com.psa.GetSymbolRequest) returns (com.psa.GetSymbolResponse);
     */
    getSymbol(input: GetSymbolRequest, options?: RpcOptions): UnaryCall<GetSymbolRequest, GetSymbolResponse>;
}
/**
 * @generated from protobuf service com.psa.Exchange
 */
export class ExchangeClient implements IExchangeClient, ServiceInfo {
    typeName = Exchange.typeName;
    methods = Exchange.methods;
    options = Exchange.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateOrder(com.psa.CreateOrderRequest) returns (com.psa.CreateOrderResponse);
     */
    createOrder(input: CreateOrderRequest, options?: RpcOptions): UnaryCall<CreateOrderRequest, CreateOrderResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateOrderRequest, CreateOrderResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetOrders(com.psa.GetOrdersRequest) returns (com.psa.GetOrdersResponse);
     */
    getOrders(input: GetOrdersRequest, options?: RpcOptions): UnaryCall<GetOrdersRequest, GetOrdersResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetOrdersRequest, GetOrdersResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetMarketDepth(com.psa.GetMarketDepthRequest) returns (com.psa.GetMarketDepthResponse);
     */
    getMarketDepth(input: GetMarketDepthRequest, options?: RpcOptions): UnaryCall<GetMarketDepthRequest, GetMarketDepthResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetMarketDepthRequest, GetMarketDepthResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetSymbol(com.psa.GetSymbolRequest) returns (com.psa.GetSymbolResponse);
     */
    getSymbol(input: GetSymbolRequest, options?: RpcOptions): UnaryCall<GetSymbolRequest, GetSymbolResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetSymbolRequest, GetSymbolResponse>("unary", this._transport, method, opt, input);
    }
}
